export default {
    user(state) { return state.user },
    isSignedIn(state) { return state.status },
    audioElement(state) { return state.audioElement },
    audioContext(state) { return state.audioContext },
    currentSong(state) { return state.currentSong },
    p(state) { return state.p },
    pointATime(state) { return state.pointATime },
    pointBTime(state) { return state.pointBTime },
    markedPointA(state) { return state.markedPointA },
    markedPointB(state) { return state.markedPointB },
    drawer(state) { return state.drawer },
    editMode(state) { return state.editMode },
    ABLoops(state) { return state.ABLoops },
    isLoading(state) { return state.isLoading },
    showSongList(state) { return state.showSongList },
    songSelected(state) { return state.songSelected },
    sourceNode(state) { return state.sourceNode },
}