export default {
    user: {},
    status: false,
    audioContext: new (window.AudioContext || window.webkitAudioContext),
    sourceNode: Object,
    gainNode: Object,
    leftGainNode: Object,
    rightGainNode: Object,
    channelSplitterNode: Object,
    mergerNode: Object,
    stereoPannerNode: Object,
    peakings: [],
    audioElement: Object,
    currentSong: Object,
    p: Object,
    pointATime: 0,
    pointBTime: 0,
    markedPointA: false,
    markedPointB: false,
    drawer: false,
    editMode: false,
    ABLoops: [],
    isLoading: false,
    showSongList: false,
    songSelected: false
}